sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        xu/qZ5EQ4CefJbekXQ09/KE4xbYBN7pvQ4tTAPpxhmHy8IBRaDf7JZpuqUfZycMoK56ZPw9GMlHBjzYUeHhmPNWgQbqFEb0FQeyDZlO01hdi0V7/Mlh4yyapAoIdyJaPlbxVHN6nFG0tm88lvIIvcZjTkt92bd4IqqF40QegOhIZ2S9zSuiEKBtrxU4EhVzAuoMgUh8DHfufmtw/R1nvLT5yN7d6+3wb76tGqIqMdBlojPQS8fUXUQb+9SkeXWSYmnKbpJEFOrZVJfIwC1d+tTLe5qXLJ7bXcg3qqdJQFpPAKFAiy5xevx+JO46EMdeq7aBRMC7T6wDX6ljqsKiA4buaa9rj6Rk3WzJKatS+YI9/xN+PvSgd+Dmgtf1QD2T0ZrkT4FnHD+4Wqm/VBEpf+29cq3AgHAS6hrQTftTZ7cGrJaAHsKCzrA8KrCrClGsgxTWkm2WzSB9F37NETspkWpq3l8pu/BMOP0nkWTf05OZrTi1iAMsmg9HAKZGgdXWmPaVGCHtZb1uQeBL0JJU6rfFj6KVca1ls7P7c8WiGvlVfnove3E2cqNQQ5rV7ydonvlogz//KhRVwZd0axLx2gxZQOrPxH09P1h6FnU2N0GkZs3jazPi/ZDhcYQWlFLk42qhzor8zIQ23PdYrIHyg0jG4hdmtV1YXMxjBpeXA1WU=
    - secure: >-
        Sj/klBixKM4dflFST1Sf+CwtG/Y2LSbWVoSRJ3JRItsmB5ft/V3TCwofrGn/CcNx3nAg8/Gdl+j6XIaP6gbCBn2578I4OJYiYpZB318KOxK2K8BF6rQR/7T4HL/UFFUhqs/JS6aPC/xLpxXLf8ovazRFf7cGMSMTQToFky1PwCwOcr8jlQfedlga5GTSChXiedDdi+axnl6Yu353t7Xc/W9nB8cDS/KFVOB6NwZthPgWRtuY5Wrm8glCGQJifJDqKw6nmUBJX+ppj+pF2UIUTvY3eIa6rOQfrwcUqYwPlLGVz4euwgs05j8LbHvdRm6+PiWwO6HRD+3cvCGYfVSm2m9eI/e+Kn1VpFgpni5JaBW3qI4cS7uoay7k6IDOb0XHgieEkd4K/fmjlS8gGbTEDGqiU+EjFBfQ5EPuEaK4PinGyodzZ/lzd2KDgqx9yNPy1wfpHVf5xZ9yeVimO/F2l/UkdQg+EkaRDVBrxPI7Dsw5PvXMOcTGHlSFqfQVBuTUOeARdqPdvkKIpUFVuPyGXCP+bU4LiP5JKq/Rl4R/5JMD4GyYTLtPfNTpPpgw6b+KSm3377dGQHvFlcG18Ym6Bc6F7yC22MdudKhFB/VNx42NWDiwIGpokZKpQ09/9zzvJxuZXdwgM0gyBKhBAw6HBP/O3l2NyfXYCRPkMZ+mLxA=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
